declare namespace NodeJS {
  interface ProcessEnv {
    LEMON_SQUEEZY_STORE_ID: string;
    LEMON_SQUEEZY_COMMUNITY_MEMBERSHIP_VARIANT_ID: string;
    LEMON_SQUEEZY_API_KEY: string;
    LEMON_SQUEEZY_WEBHOOK_COMMUNITY_SIGNING_SECRET: string;
    TELEGRAM_COMMUNITY_BOT_TOKEN: string;
    TELEGRAM_COMMUNITY_GROUP_ID: string;
    TELEGRAM_COMMUNITY_WEBHOOK_SECRET_TOKEN: string;
    TELEGRAM_COMMUNITY_BOT_ID: string;
  }
}
